# Generated by Django 3.2.3 on 2021-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(to='mainapp.Brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
