# Generated by Django 3.2.3 on 2021-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210603_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChekOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.TextField(max_length=70)),
                ('password', models.PositiveIntegerField()),
                ('company', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=70)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=70)),
                ('sity', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('zip_code', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=150)),
                ('regions', models.CharField(max_length=150)),
                ('phone', models.PositiveIntegerField()),
                ('mobil_phone', models.PositiveIntegerField()),
                ('fax', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=5000)),
            ],
        ),
    ]
