# Generated by Django 3.2.3 on 2021-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_chekout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chekout',
            name='country',
        ),
        migrations.RemoveField(
            model_name='chekout',
            name='regions',
        ),
        migrations.AlterField(
            model_name='chekout',
            name='password',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='chekout',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
