# Generated by Django 3.2 on 2021-06-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210605_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(default='New Message', max_length=50),
        ),
    ]
