# Generated by Django 3.2 on 2021-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(default='None', max_length=70),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
